// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxkpzczkoshaudtiuhea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4a3B6Y3prb3NoYXVkdGl1aGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjEwMDksImV4cCI6MjA2OTE5NzAwOX0.uV8-2rxs1RtlkdUAxI9U79fjGDZ4qL9VbaSqBh8Nhjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});